package com.alphawallet.app.entity;

public enum TransactionType
{
    UNKNOWN,
    LOAD_NEW_TOKENS,
    TRANSFER_TO,
    RECEIVE_FROM,
    CONSTRUCTOR,
    TERMINATE_CONTRACT,
    UNKNOWN_FUNCTION,
    INVALID_OPERATION,
    TRANSFER_FROM,
    ALLOCATE_TO,
    APPROVE,
    RECEIVED,
    SEND,
    SEND_ETH,
    WITHDRAW,
    DEPOSIT,
    CONTRACT_CALL,
    ILLEGAL_VALUE;
}
